/* Copyright 2022 The MathWorks, Inc. */

#pragma once

#include "package.h"

#ifdef BUILDING_MW_GRPC_CLIENTS

/* This header is being included by files inside this module */

#define MW_GRPC_CLIENTS_EXPORT_CLASS    DLL_EXPORT_SYM
#define MW_GRPC_CLIENTS_EXPORT_FRIEND   DLL_EXPORT_SYM
#define MW_GRPC_CLIENTS_EXPORT_FCN      DLL_EXPORT_SYM
#define MW_GRPC_CLIENTS_EXPORT_TEMPLATE DLL_EXPORT_TEMPLATE

#define MW_GRPC_CLIENTS_EXPORT_EXTERN_C extern "C" DLL_EXPORT_SYM

#define MW_GRPC_CLIENTS_EXPORT_VAR     extern
#define MW_GRPC_CLIENTS_EXPORT_VAR_DEF DLL_EXPORT_SYM

#define MW_GRPC_CLIENTS_EXPORT DLL_EXPORT_SYM

#else

/* This file is being include by other TMW internal modules */
#define MW_GRPC_CLIENTS_EXPORT_CLASS    DLL_IMPORT_SYM
#define MW_GRPC_CLIENTS_EXPORT_FRIEND   DLL_IMPORT_SYM
#define MW_GRPC_CLIENTS_EXPORT_FCN      DLL_IMPORT_SYM
#define MW_GRPC_CLIENTS_EXPORT_TEMPLATE DLL_EXPORT_TEMPLATE

#define MW_GRPC_CLIENTS_EXPORT_EXTERN_C extern "C" DLL_IMPORT_SYM

#define MW_GRPC_CLIENTS_EXPORT_VAR extern DLL_IMPORT_SYM

#define MW_GRPC_CLIENTS_EXPORT DLL_IMPORT_SYM
#endif
